plugins {
    id "com.android.library"
}

android {
    namespace = "dev.example.module"
    compileSdk = 36

    defaultConfig {
        minSdk = 23
        consumerProguardFiles "consumer-rules.pro"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}
